# Generated by Django 4.2.6 on 2023-11-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=15)),
                ('hostname', models.CharField(max_length=15)),
                ('address_city', models.CharField(max_length=30)),
                ('address_street', models.CharField(max_length=50)),
                ('addrss_building', models.IntegerField()),
            ],
        ),
    ]
