# Generated by Django 4.2.6 on 2023-11-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev',
            name='addrss_building',
            field=models.CharField(max_length=7),
        ),
    ]
