# Generated by Django 4.2.6 on 2023-11-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_dev_addrss_building'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dev',
            old_name='addrss_building',
            new_name='adderss_building',
        ),
        migrations.RenameField(
            model_name='dev',
            old_name='type',
            new_name='dev_type',
        ),
        migrations.AddField(
            model_name='dev',
            name='mgmt_inband_ip',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='dev',
            name='mgmt_loopback_ip',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='dev',
            name='territory_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
