# Generated by Django 4.2.6 on 2023-11-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_rename_addrss_building_dev_adderss_building_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dev',
            old_name='adderss_building',
            new_name='address_building',
        ),
    ]
