# Generated by Django 4.2.6 on 2023-11-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_rename_adderss_building_dev_address_building'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dev',
            new_name='Device',
        ),
    ]
