# Generated by Django 4.2.7 on 2023-11-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_rename_dev_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mrf',
            field=models.CharField(blank=True, choices=[('SZ', 'Северо-запад'), ('DV', 'Дальний восток'), ('VL', 'Волга'), ('SI', 'Сибирь'), ('UG', 'Юг'), ('UR', 'Урал'), ('CN', 'Центр')], max_length=2, null=True),
        ),
    ]
