# Generated by Django 4.2.7 on 2023-11-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_address_devices_nodes_delete_device'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devices',
            new_name='Device',
        ),
        migrations.RenameModel(
            old_name='Nodes',
            new_name='Node',
        ),
    ]
