# Generated by Django 4.2.7 on 2023-11-27 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_node_hostname_alter_node_support_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='hostname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
    ]
