# Generated by Django 4.2.7 on 2023-11-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_alter_node_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='firmware',
            field=models.CharField(default='6.4', max_length=15),
        ),
        migrations.AlterField(
            model_name='device',
            name='dev_type',
            field=models.CharField(choices=[('F', 'Fortigate'), ('К', 'Континент'), ('T', 'Tufin')], max_length=1),
        ),
    ]
