# Generated by Django 4.2.7 on 2023-11-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_node_firmware_alter_device_dev_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='type',
        ),
    ]
