# Generated by Django 4.2.7 on 2023-11-27 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_remove_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='hostname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='dev_type',
            field=models.CharField(choices=[('F', 'Fortigate'), ('К', 'Континент'), ('T', 'Tufin')], max_length=20),
        ),
    ]
