# Generated by Django 4.2.7 on 2023-11-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_remove_device_dev_type_remove_device_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='ups',
        ),
        migrations.AddField(
            model_name='node',
            name='ups',
            field=models.CharField(default='Имеется', max_length=200),
        ),
    ]
