# Generated by Django 4.2.7 on 2023-12-08 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_firmware_remove_node_build_remove_node_firmware_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='dev_type',
            field=models.CharField(choices=[('FG', 'FortiGate'), ('FSW', 'FortiSWitch'), ('FAU', 'FortiAuthenticator'), ('FAZ', 'FortiAnalyzer'), ('FMG', 'FortiManager'), ('NG', 'NGate'), ('TS', 'TufinServer'), ('TC', 'TufinCollector'), ('К', 'Континент'), ('КЦ', 'Континент (ЦУС)')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='firmware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.firmware'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
