# Generated by Django 4.2.7 on 2023-12-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_alter_device_dev_type_alter_device_firmware_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='firmware',
            field=models.CharField(default='6.4.13', max_length=15),
        ),
    ]
